apiVersion: v1
kind: ConfigMap
metadata:
  namespace: nginx-app
  name: configmap-html
  annotations:
    reloader.stakater.com/search: "true"
data:
  index.html: |
    <html>
    <head>
        <title>Nginx app</title>
    </head>
    <body>    
    <h1>Nginx simple app in kubernetes cluster k3s</h1>
    <p>I use specific configmap</p>
    </body>
    </html>