apiVersion: v1
kind: ConfigMap
metadata:
  namespace: nginx-app
  name: configmap-conf
  annotations:
    reloader.stakater.com/search: "true"
data:
  index.html: |
    server {
        listen 80;
        location /{
            root /usr/share/nginx/html;
            index index.html;
        }
    }